### ISSUE TITLE
Wrong pom id

### ISSUE THREAD

**Issue by Alexdruso** [TonyFPY/Frogger_G52SWM#1]
In your pom, I think your id is badly initialized. As you can see this results in more than 8k projects importing yours as a dependency and this happens every time someone imports JavaFX. 
I suggest you fix this.

**Comment by TonyFPY** [comment]
> In your pom, I think your id is badly initialized. As you can see this results in more than 8k projects importing yours as a dependency and this happens every time someone imports JavaFX.
> I suggest you fix this.

Thanks for pointing out my problem! I just followed the steps from the official website when I tried to deployed Maven Framework. Since the program could run on my school's lab, I didn't pay much attention to pom.xml. Could you please help me to fix that? How can I set the right groupId and artifactId in my pom.xml?

**Comment by Alexdruso** [comment]
You set the ID correctly and now it should be fixed, but I still see your project in my dependencies 😕
Are the repos using your project still increasing?

**Comment by TonyFPY** [comment]
> You set the ID correctly and now it should be fixed, but I still see your project in my dependencies 😕
> Are the repos using your project still increasing?

No. I cannot see the number of repos using my project now. I wonder if there is anything else to fix.

**Comment by danthe1st** [comment]
The problem might be that the iml file is still named `javafx-controls.iml`.
