### ISSUE TITLE
Wrong groupId and artifactId in pom.xml

### ISSUE THREAD

**Issue by kientuong114** [TonyFPY/Frogger_G52SWM#2]
Hi, just letting you know that you've set the wrong groupId and artifactId in your pom.xml.
This makes it so that every project that uses JavaFX (and JavaFX controls) has the dependency graph that links back to your project.
You can see that there are 8000+ project that are dependant on your project which of course is not desirable :)

This is not too serious but it'd be nice if it was fixed.

**Comment by TonyFPY** [comment]
Thank you for pointing out my problem!  Since I just followed the steps from the official website and it worked on my school's lab, I didn't care much about it at that time. Could you help me on how to fix this?

**Comment by TonyFPY** [comment]
> Hi, just letting you know that you've set the wrong groupId and artifactId in your pom.xml.
> This makes it so that every project that uses JavaFX (and JavaFX controls) has the dependency graph that links back to your project.
> You can see that there are 8000+ projects that are dependant on your project which of course is not desirable :)
> 
> This is not too serious but it'd be nice if it was fixed.

Thanks for pointing out my problem! I just followed the steps from the official website when I tried to deployed Maven Framework. Since the program could run on my school's lab, I didn't pay much attention to pom.xml. Could you please help me to fix that? How can I set the right groupId and artifactId in my pom.xml?
